package com.pojo.classes;
// Generated 14 Apr, 2016 5:18:49 PM by Hibernate Tools 4.3.1



/**
 * Beds generated by hbm2java
 */
public class Beds  implements java.io.Serializable {


     private String code;
     private String ward;
     private String status;

    public Beds() {
    }

	
    public Beds(String code) {
        this.code = code;
    }
    public Beds(String code, String ward, String status) {
       this.code = code;
       this.ward = ward;
       this.status = status;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getWard() {
        return this.ward;
    }
    
    public void setWard(String ward) {
        this.ward = ward;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


