package com.pojo.classes;
// Generated 14 Apr, 2016 5:18:49 PM by Hibernate Tools 4.3.1



/**
 * Laboratory generated by hbm2java
 */
public class Laboratory  implements java.io.Serializable {


     private String code;
     private String description;
     private String charges;

    public Laboratory() {
    }

	
    public Laboratory(String code) {
        this.code = code;
    }
    public Laboratory(String code, String description, String charges) {
       this.code = code;
       this.description = description;
       this.charges = charges;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCharges() {
        return this.charges;
    }
    
    public void setCharges(String charges) {
        this.charges = charges;
    }




}


